server:
  port: 3000

db:
  type: 'mysql'
  port: 3306
  host: 'localhost'
  username: 'your name here!'
  password: 'your password here!'

jwt:
  access:
    expiresIn: 3600
    secret: 'SceretSauce'
  refresh:
    expiresIn: 2592000
    secret: 'Refreshments'

file:
  path: 'public'